---
- name: Add apt-fast key
  apt_repository:
    repo: "ppa:apt-fast/stable"
    state: present
    update_cache: yes

- name: Install apt-fast
  apt:
    name: apt-fast 
    state: present
  when: ansible_os_family == 'Debian'
