Vagrant.configure("2") do |config|

  # $1 is an parameter, will be injected later
  # see: server.vm.provision :shell, inline: $script_common, args: %x[whoami]
  $script_common = <<SCRIPT
  export DEBIAN_FRONTEND=noninteractive

  apt-get update -y
  apt-get install sshpass -y
  
  useradd -m $1 -p $(openssl passwd -1 12345)
  usermod -aG sudo $1
  mkdir -p /home/$1/.ssh
  cat '/vagrant/id_rsa.pub' >> /home/$1/.ssh/authorized_keys
SCRIPT

  server_configs = [
    {"hostname" => "ci", "ip" => "192.168.33.10", "memory_size" => "1024"}
  ]
  server_configs.each do |server_config|
    config.vm.define server_config['hostname'] do |server|
      server.vm.hostname = server_config['hostname']

      server.vm.box = "bento/ubuntu-16.04"
      # server.vm.box_url = "https://vagrantcloud.com/bento/whoamiubuntu-16.04"

      server.vm.network :private_network, ip: server_config['ip']
      server.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", server_config['memory_size']]

        # suggested fix for slow network performance
        # see https://github.com/mitchellh/vagrant/issues/1807
        # DNS Not Working, see https://serverfault.com/a/506206/500039
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

        # change the network card hardware for better performance
        v.customize ["modifyvm", :id, "--nictype1", "virtio" ]
        v.customize ["modifyvm", :id, "--nictype2", "virtio" ]
      end

      # update machine
      server.vm.provision :shell, inline: $script_common, args: %x[whoami]

    end
  end
end